### PR TITLE
svg experiment

### PR DESCRIPTION
**Pull request by laduke**
hi,
just for my own benefit I wanted to go through elm architecture again. This couldn't be merged or anything in any meaningful way. Just wanted to share the small example.

### CODE REVIEW

**Comment by laduke** [comment]
I had incorrectly assumed that you can't/shouldn't nest svgs/viewports. After 2 minutes of reading, I think each square should be in it's own viewport, so you could animate a diamond entering or leaving a square.

**Comment by datagrok** [comment]
Nice. I'd suggest rebasing this on 78e679c, the new "inital commit" in this repo, to make it clear that it's its own line of development unrelated to the previous `master` and `elm17` branches.

`git rebase --onto 78e679c elm17 tl-svg`

Also, I had to capitalize `Board.elm` and `Square.elm` to make it work on my system.

**Comment by laduke** [comment]
I think I could manage to rebase it locally, but how would I then push it to my github repo and still be able to use this pull-request?

**Comment by oldfartdeveloper** [comment]
@laduke I look forward to looking at your efforts this evening; thanks for submitting.  I had suspected that you could nest svgs but hadn't looked into it further; thanks for confirming.

**Comment by laduke** [comment]
closing

**Pull request closed without merging**
